### ISSUE TITLE
Update readme with roadmap and more info

### ISSUE THREAD

**Issue by DasithKuruppu** [DasithKuruppu/uglyBot#10]
- [x]  Add more essential info on usage.
- [x]  Add ugly Bot image.
- [x]  Add in road-map
